# Generated by Django 5.0.6 on 2024-08-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.CharField(default=True, max_length=1000),
        ),
    ]
